---
- name: Install nginx
  hosts: all
  become: true
  tasks:
    - name: Install nginx on RedHat-based
      yum: 
        name: nginx
        state: latest
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install nginx on Debian-based
      apt:
        name: nginx
        state: latest
      when: ansible_facts['os_family'] == "Debian"

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: true 
