---
- name: Rolling update
  hosts: all
  serial: 
    - 1
    - 2
  max_fail_percentage: 10
  tasks:
  - name: Task 1
    command: sleep 2
  - name: Task 2
    command: sleep 2
  - name: Task 3
    command: sleep 2
  - name: Fail task
    command: /bin/false
    when: inventory_hostname is search("_2")
