---
- name: Install apache
  hosts: centos, ubuntu
  become: true
  vars:
    package_name:
      Ubuntu: apache2 
      CentOS: httpd
  tasks: 
    - name: install apache
      package: 
        name: "{{ package_name[ansible_distribution ]}}"
        state: present 
    - name: start and enable apache
      systemd:
        name: "{{ package_name[ansible_distribution ]}}"
        state: started
        enabled: true
